#!/bin/bash
set -e

if [ $# -ne 1 ]; then
  echo "emulate-device1 expect one argument: <API_KEY>"
  exit 1
fi

API_KEY=$1

./src/resolvePackages.js --apiKey ${API_KEY} --unitId device2 --packages '[{ "reference":"io.barracks.demo.app1", "version":"v1" }]' --customClientData '{ "type":"beta" }'

read  -n 1 -p "Press enter to install app1 v2, and contact Barracks with app2enabled in the customClientData..."

./src/resolvePackages.js --apiKey ${API_KEY} --unitId device2 --packages '[{ "reference":"io.barracks.demo.app1", "version":"v2" }]' --customClientData '{ "type":"beta", "extra": { "app2":true } }'