#!/bin/bash
set -e

if [ $# -ne 1 ]; then
  echo "emulate-device1 expect one argument: <API_KEY>"
  exit 1
fi

API_KEY=$1

./src/resolvePackages.js --apiKey ${API_KEY} --unitId device1 --packages '[]'

read  -n 1 -p "Press enter to install package, and contact Barracks again..."

./src/resolvePackages.js --apiKey ${API_KEY} --unitId device1 --packages '[{ "reference":"io.barracks.demo.app1", "version":"v1" }]'