#!/bin/bash
set -e

OLD_BARRACKS_ENABLE_V2=$BARRACKS_ENABLE_V2
export BARRACKS_ENABLE_V2="1"
export BARRACKS_BASE_URL="https://app.barracks.io"
export BARRACKS_MQTT_ENDPOINT="mqtt://mqtt.barracks.io"
export BARRACKS_ENABLE_EXPERIMENTAL=1

echo "-----------------------------------------"
echo "-- Connecting to account ${LOGIN}"
echo "-----------------------------------------"
if [ -e "~/.barracks/barracks.json" ]; then
  rm -rf "~/.barracks/barracks.json"
fi
barracks login

echo "-----------------------------------------"
echo "-- Creating 'Windows' filter..."
echo "-----------------------------------------"
barracks filter create --name windows --query '{ "eq": { "customClientData.os": "windows" } }'
echo "-----------------------------------------"
echo "-- Creating 'Linux' filter..."
echo "-----------------------------------------"
barracks filter create --name linux --query '{ "eq": { "customClientData.os": "linux" } }'
echo "-----------------------------------------"
echo "-- Creating 'Send logs' filter..."
echo "-----------------------------------------"
barracks filter create --name send_logs --query '{ "and": [ { "eq": { "customClientData.os": "linux" } },{ "eq": { "customClientData.state.sendLogs": true } } ] }'

echo "-----------------------------------------"
echo "-- Creating firmware for linux"
echo "-----------------------------------------"
barracks package create --reference io.barracks.firmware.linux --name "Linux Firmware"
barracks package version create --versionId v1 --name "Version 1" --packageReference io.barracks.firmware.linux --file packages/linux_firmware.js --metadata '{ "billing": "free" }'

echo "---------------------------------------------------------------"
echo "-- Uploading deployment plan for io.barracks.firmware.linux..."
echo "---------------------------------------------------------------"
cat packages/linux_firmware_plan.json | barracks package plan publish

echo "-------------------------------------"
echo "-- Creating firmware for windows"
echo "-------------------------------------"
barracks package create --reference io.barracks.firmware.windows --name "Windows Firmware"
barracks package version create --versionId v1 --name "Version 1" --packageReference io.barracks.firmware.windows --file packages/windows_firmware.js --metadata '{ "billing": "paying" }'

echo "---------------------------------------------------------------------"
echo "-- Uploading deployment plan for io.barracks.firmware.windows..."
echo "---------------------------------------------------------------------"
cat packages/windows_firmware_plan.json | barracks package plan publish

echo "---------------------------------------"
echo "-- Creating firmware for log sending"
echo "---------------------------------------"
barracks package create --reference io.barracks.firmware.logs --name "Send Logs Firmware"
barracks package version create --versionId v1 --name "Version 1" --packageReference io.barracks.firmware.logs --file packages/send_logs_firmware.js

echo "-----------------------------------------------------------------------"
echo "-- Uploading deployment plan for io.barracks.firmware.logs..."
echo "-----------------------------------------------------------------------"
cat packages/send_logs_firmware_plan.json | barracks package plan publish

barracks logout

export BARRACKS_ENABLE_V2=$OLD_BARRACKS_ENABLE_V2

