#!/bin/bash
set -e

OLD_BARRACKS_ENABLE_V2=$BARRACKS_ENABLE_V2
export BARRACKS_ENABLE_V2="1"

echo "-----------------------------------------"
echo "-- Installing / upgrading barracks CLI..."
echo "-----------------------------------------"
npm install -g barracks-cli
npm install

echo "-----------------------------------------"
echo "-- Connecting to account ${LOGIN}"
echo "-----------------------------------------"
if [ -e "~/.barracks/barracks.json" ]; then
  rm -rf "~/.barracks/barracks.json"
fi
barracks login

echo "-----------------------------------------"
echo "-- Creating 'All' filter..."
echo "-----------------------------------------"
barracks filter create --name all --query '{ "regex": { "unitId":".*" } }'
echo "-----------------------------------------"
echo "-- Creating 'Screen' filter..."
echo "-----------------------------------------"
barracks filter create --name screen --query '{ "regex": { "customClientData.hardware.screen":".+" } }'
echo "-----------------------------------------"
echo "-- Creating 'Speed Sensor' filter..."
echo "-----------------------------------------"
barracks filter create --name speed-sensor --query '{ "regex": { "customClientData.hardware.speed-sensor":".+" } }'
echo "-----------------------------------------"
echo "-- Creating 'Trafic counter' filter..."
echo "-----------------------------------------"
barracks filter create --name trafic-counter --query '{ "regex": { "customClientData.hardware.trafic-counter":".+" } }'

echo "-----------------------------------------"
echo "-- Creating firmware for screen"
echo "-----------------------------------------"
barracks package create --reference io.barracks.firmware.screen --name "Screen Firmware"
barracks package version create --versionId v1 --name "Version 1" --packageReference io.barracks.firmware.screen --file packages/screen_firmware.js --metadata '{ "text": "This is the default text to display on the screen" }'

echo "---------------------------------------------------------------"
echo "-- Uploading deployment plan for io.barracks.firmware.screen..."
echo "---------------------------------------------------------------"
cat packages/screen_firmware_plan.json | barracks package plan publish

echo "-------------------------------------"
echo "-- Creating firmware for speed sensor"
echo "-------------------------------------"
barracks package create --reference io.barracks.firmware.speed-sensor --name "Speed Sensor Firmware"
barracks package version create --versionId v1 --name "Version 1" --packageReference io.barracks.firmware.speed-sensor --file packages/speed_sensor_firmware.js

echo "---------------------------------------------------------------------"
echo "-- Uploading deployment plan for io.barracks.firmware.speed-sensor..."
echo "---------------------------------------------------------------------"
cat packages/speed_sensor_firmware_plan.json | barracks package plan publish

echo "---------------------------------------"
echo "-- Creating firmware for trafic counter"
echo "---------------------------------------"
barracks package create --reference io.barracks.firmware.trafic-counter --name "Trafic counter Firmware"
barracks package version create --versionId v1 --name "Version 1" --packageReference io.barracks.firmware.trafic-counter --file packages/trafic_counter_firmware.js

echo "-----------------------------------------------------------------------"
echo "-- Uploading deployment plan for io.barracks.firmware.trafic_counter..."
echo "-----------------------------------------------------------------------"
cat packages/trafic_counter_firmware_plan.json | barracks package plan publish
barracks logout

export BARRACKS_ENABLE_V2=$OLD_BARRACKS_ENABLE_V2

