#!/bin/bash

set -e

if [ $# -ne 1 ]; then
  echo "emulate-sensor-device expect one argument: <API_KEY>"
  exit 1
fi

echo "-----------------------------------------------------------"
echo "-- Checking if we need to install or update Barracks SDK --"
echo "-----------------------------------------------------------"
npm install

echo "--------------------------------"
echo "-- Barracsk SDK is up to date --"
echo "--------------------------------"
echo ""

echo "Cleaning existing packages for sensor device..."
rm -rf sensor-device-packages/
mkdir sensor-device-packages

echo "starting sensor device..."

npm run start sensor-device $1 "./sensor-device_customClientData.json"