#!/bin/bash

set -e

if [ $# -ne 1 ]; then
  echo "emulate-device1 expect one argument: <API_KEY>"
  exit 1
fi

echo "-----------------------------------------------------------"
echo "-- Checking if we need to install or update Barracks SDK --"
echo "-----------------------------------------------------------"
npm install

echo "--------------------------------"
echo "-- Barracsk SDK is up to date --"
echo "--------------------------------"
echo ""

echo "Cleaning existing packages for device 1..."
rm -rf device-1-packages/
mkdir device-1-packages

echo "starting device 1..."

npm run start device-1 $1 "./device1_customClientData.json"
