#!/bin/bash

set -e

if [ $# -ne 1 ]; then
  echo "emulate-windows-device expect one argument: <API_KEY>"
  exit 1
fi

echo "-----------------------------------------------------------"
echo "-- Checking if we need to install or update Barracks SDK --"
echo "-----------------------------------------------------------"
npm install

echo "--------------------------------"
echo "-- Barracsk SDK is up to date --"
echo "--------------------------------"
echo ""

echo "Cleaning existing packages for sensor device..."
rm -rf windows-device-packages/
mkdir windows-device-packages

echo "starting windows device..."

npm run start windows-device $1 "./windows-device_customClientData.json"
