#!/bin/bash

set -e

if [ $# -ne 1 ]; then
  echo "emulate-linux-device expect one argument: <API_KEY>"
  exit 1
fi

echo "-----------------------------------------------------------"
echo "-- Checking if we need to install or update Barracks SDK --"
echo "-----------------------------------------------------------"
npm install

echo "--------------------------------"
echo "-- Barracsk SDK is up to date --"
echo "--------------------------------"
echo ""

echo "Cleaning existing packages for sensor device..."
rm -rf linux-device-packages/
mkdir linux-device-packages

echo "starting linux device..."

npm run start linux-device $1 "./linux-device_customClientData.json"