#!/bin/bash

set -e

if [ $# -ne 1 ]; then
  echo "emulate-display-device expect one argument: <API_KEY>"
  exit 1
fi

echo "-----------------------------------------------------------"
echo "-- Checking if we need to install or update Barracks SDK --"
echo "-----------------------------------------------------------"
npm install

echo "--------------------------------"
echo "-- Barracsk SDK is up to date --"
echo "--------------------------------"
echo ""

echo "Cleaning existing packages for sensor device..."
rm -rf display-device-packages/
mkdir display-device-packages

echo "starting sensor device..."

npm run start display-device $1 "./display-device_customClientData.json"
